import type { Step } from './sion-scenario'

export const LAUSANNE_SCENARIO: Step[] = [
  {
    id: 1,
    title: 'Le Parvis de la Gare (Le Réveil)',
    context: "Commence par te lever. C'est dur, je sais. Hier soir, tu as juré que tu pouvais prendre le M2 à la nage. Trouve l'entrée du métro, mais on va y aller à pied.",
    instruction: 'Quelle est la couleur du 2ème anneau olympique visible sur le bâtiment de la gare ?',
    type: 'text',
    gpsCoordinates: '46.517278,6.629286',
    expectedAnswer: 'jaune',
    penalty: "Le capitaine doit annoncer un train imaginaire à voix forte : « Le train InterCity à destination de la Gueule de Bois partira voie 9 3/4. »",
    points: 100,
  },
  {
    id: 2,
    title: 'Le Bas du Petit-Chêne (Le Mur)',
    context: "Face à toi, la rue du Petit-Chêne. 12% d'inclinaison. Hier soir, tu as essayé de la monter en moonwalk. Prouve-moi que tes mollets répondent encore.",
    instruction: "Filmez un membre de l'équipe monter quelques mètres de la rue du Petit-Chêne en moonwalk.",
    type: 'video',
    gpsCoordinates: '46.517983,6.629397',
    penalty: "Réaliser une chorégraphie de 10 secondes en mime d'alpiniste (avec piolets imaginaires) en pleine montée.",
    points: 100,
  },
  {
    id: 3,
    title: 'Lausanne Palace (La Haute Société)',
    context: "Tu as survécu à l'ascension. Devant le Lausanne Palace, tu as essayé de soudoyer le portier avec un ticket de kebab pour avoir une suite. Retrouve un peu de dignité.",
    instruction: "Combien de colonnes se trouvent devant l'entrée principale ?",
    type: 'text',
    gpsCoordinates: '46.519690,6.630733',
    expectedAnswer: '6',
    penalty: "Marcher sur 10 mètres avec une démarche exagérément snob en saluant les passants avec un « Salutations, manant » très poli.",
    points: 100,
  },
  {
    id: 4,
    title: 'Parc de Montbenon (La Vision Spatiale)',
    context: "Petit détour par les jardins. Face au lac, tu as cru voir le monstre du Léman. C'était juste un pédalo, redescends sur terre.",
    instruction: 'Photo de groupe devant la statue de Guillaume Tell avec votre meilleure grimace.',
    type: 'photo',
    gpsCoordinates: '46.520187,6.626663',
    penalty: 'Faire prendre la pose du Titanic à deux membres de l\'équipe face au lac pendant 10 secondes.',
    points: 100,
  },
  {
    id: 5,
    title: 'Place Saint-François (La Confession)',
    context: "Direction le centre névralgique. Devant l'église Saint-François, tu as voulu confesser tes péchés au chauffeur du bus 1. Il n'a pas voulu t'absoudre.",
    instruction: "Compte le nombre de marches que compte l'entrée principale, ajoute 20, fais x2, +19, retire 10 et donne le résultat.",
    type: 'text',
    gpsCoordinates: '46.519718,6.632897',
    expectedAnswer: '69',
    penalty: 'Chanter « Alléluia » en chœur (et très fort) en imitant une chorale de gospel.',
    points: 100,
  },
  {
    id: 6,
    title: 'Place de la Palud (La Justice Aveugle)',
    context: "Descends vers la Palud. Devant la fontaine, tu as longuement débattu avec la statue de la Justice. Tu as perdu.",
    instruction: 'Filmez-vous en train de faire un gangnam style devant la fontaine. Minimum 5 secondes de vidéo.',
    type: 'video',
    gpsCoordinates: '46.521824,6.633214',
    penalty: 'Un joueur doit se bander les yeux (ou les fermer très fort) et tenir en équilibre sur une jambe pendant que les autres font semblant de le plaider coupable.',
    points: 100,
  },
  {
    id: 7,
    title: 'Les Escaliers du Marché (Le Faux Espoir)',
    context: "Regarde ces magnifiques escaliers en bois. Hier, tu as voulu les descendre en luge. Heureusement, tu n'avais pas de luge.",
    instruction: 'Trouve en quelle année a été fondée la maison de défense, chasse et tir.',
    type: 'text',
    gpsCoordinates: '46.522341,6.634067',
    expectedAnswer: '1808',
    penalty: 'Faire une course au ralenti (façon Alerte à Malibu) sur les 5 prochaines marches.',
    points: 100,
  },
  {
    id: 8,
    title: 'Place de la Louve (La Cachette)',
    context: "La place de la mairie. C'est ici que tu t'es caché derrière une poubelle en croyant échapper aux mangemorts. Sortez de l'ombre.",
    instruction: 'Imitez un loup qui hurle à la mort en plein milieu de la place. Activez le capteur et tenez 85% de volume pendant 3 secondes.',
    type: 'decibel',
    gpsCoordinates: '46.521674,6.632367',
    penalty: 'Un joueur doit tourner 10x sur lui-même et faire un high-five au caméraman.',
    points: 100,
  },
  {
    id: 9,
    title: 'Rue Saint-Laurent (Le Bain de Foule)',
    context: "Retour dans l'agitation. Dans cette rue piétonne, tu as essayé de lancer une chenille géante. Personne n'a suivi. C'est le moment de te rattraper.",
    instruction: "Tentez une chenille humaine en invitant des inconnus à se joindre à vous ! Celui en tête doit filmer en selfie.",
    type: 'video',
    gpsCoordinates: '46.522374,6.630803',
    penalty: 'Ramassez 10 mégots et jetez-les à la poubelle.',
    points: 100,
  },
  {
    id: 10,
    title: 'Le Grand-Pont (Le Vertige)',
    context: "Mets-toi au milieu du pont et regarde en bas. C'est là que tu as menacé de jeter ton téléphone parce qu'il n'avait plus de batterie. Ne fais pas ça.",
    instruction: 'Placez-vous sur le pont et prenez la plus belle photo de groupe en faisant un Dab.',
    type: 'photo',
    gpsCoordinates: '46.521054,6.630754',
    penalty: 'Tout le groupe s\'aligne contre la rambarde et hurle « On arrive en baaaas ! » en regardant vers le Flon.',
    points: 100,
  },
  {
    id: 11,
    title: "Place de l'Europe (Les Arches)",
    context: "Tu redescends enfin. Sous ces arches, tu te prenais pour Batman surveillant Gotham City. Trouve la bonne planque.",
    instruction: "Trouve les dates correspondant à notre chère enseignante, Hélène Monastier — cela te donne un code à 8 chiffres.",
    type: 'text',
    gpsCoordinates: '46.520455,6.631051',
    expectedAnswer: '18821976',
    penalty: "Interpeller un passant poliment pour lui demander de valider un « check » (tape m'en cinq).",
    points: 100,
  },
  {
    id: 12,
    title: "Place du Flon (L'Arrivée Triomphale)",
    context: "Bienvenue dans l'arène. C'est ici que tu as échangé ta dignité contre une dernière bière. Va au centre du quartier.",
    instruction: "Rendez-vous à l'esplanade du Flon et criez tous ensemble : APÉRO !!! Activez le capteur et atteignez 85% de volume pour valider ce dernier défi !",
    type: 'decibel',
    gpsCoordinates: '46.521458,6.627343',
    penalty: 'Mets une story Facebook ou Instagram disant que tu as échoué au jeu du Blackout !',
    points: 100,
  },
]

export const TOTAL_STEPS = 12
export const POINTS_PER_STEP_BASE = 100
